<definitions name ='calculatorService'
    targetNamespace="http://example.com/wsdl/calculatorService.wsdl"
    xmlns:soap ="http://schemas.xmlsoap.org/wsdl/soap/"
    xmlns:tns="http://localhost:8080/calculatorService"
    xmlns="http://schemas.xmlsoap.org/wsdl/">

    <message name ="AddRequest">
        <part name="num1" type ="xsd:int" />
        <part name="num2" type ="xsd:int" />
    </message>

    <message name ="AddResponse">
        <part name="result" type ="xsd:int" />
    </message>

    <portType name="Calculator_portType"> 
        <operation name ="addNumbers">
            <input message="tns:AddRequest" />
            <output message="tns:AddResponse"/>
        </operation>
    </portType>

    <binding name="Calculator_Binding" type="tns:Calculator_PortType">
        <soap:binding style ="document" transport="http://schemas.xmlsoap.org/soap/http" />
    </binding>

    <service name="CalculatorService">
        <port name="Calculator_port" binding="tns:Calculator_Binding">
            <soap:address location ="http://localhost:8080/CalculatorService" />
        </port>
    </service>
</definitions>